dist: trusty
sudo: false

language: node_js
node_js: "8"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0" # Configuration for e2e tests
  - yarn global add greenkeeper-lockfile@1 # Connection with Greenkeeper
before_script: greenkeeper-lockfile-update # Connection with Greenkeeper
after_script: greenkeeper-lockfile-upload # Connection with Greenkeeper

cache:
  yarn: true
  directories:
     - ./node_modules

stages:
  - test
  - deploy
  - release

jobs:
  include:
    
    - stage: test # Unit tests
      env: TEST=Unit tests
      script:
        - npm run lint
        - npm run ci:test
    
    - stage: test # Unit tests
      env: TEST=e2e tests
      script:
        - xvfb-run -a npm run ci:e2e

    - stage: deploy # Deploy to DEV environment
      env: URL=https://samuel-fernandez-dev.herokuapp.com/ # Here we need to make it explicit
      if: type = push AND (NOT branch = master) # Deploy only run for PUSH, but avoid master
      script: skip # Default script is npm test, which we want to skip
      after_deploy:
        - xvfb-run -a npm run ci:e2e-remote
      deploy:
        provider: heroku
        app: $HEROKU_APP_DEV # This deployment is only for PR
        api_key:
          - $HEROKU_TOKEN # Generated running heroku auth:token
        on:
          all_branches: true
    
    - stage: deploy # Deploy to STG environment
      env: URL=https://samuel-fernandez-stg.herokuapp.com/ # Here we need to make it explicit
      if: (NOT type = pull_request) AND branch = master
      script: skip # Default script is npm test, which we want to skip
      after_deploy:
        - xvfb-run -a npm run ci:e2e-remote
      deploy:
        provider: heroku
        app: $HEROKU_APP_STG # This deployment is a pre-release phase
        api_key:
          - $HEROKU_TOKEN # Generated running heroku auth:token

    - stage: release # Release to PRD environment
      env: URL=https://samuel-fernandez.herokuapp.com/ # Here we need to make it explicit
      if: (NOT type = pull_request) AND branch = master # Only for for master build
      script: skip # Default script is npm test, which we want to skip
      after_deploy:
        - xvfb-run -a npm run ci:e2e-remote
      deploy:
        provider: heroku
        app: $HEROKU_APP_PRD # This deployment is the release
        api_key:
          - $HEROKU_TOKEN # Generated running heroku auth:token
