dist: trusty
sudo: false

language: node_js
node_js: "8"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0" # Configuration for e2e tests
  - yarn global add greenkeeper-lockfile@1 # Connection with Greenkeeper
before_script: greenkeeper-lockfile-update # Connection with Greenkeeper
after_script: greenkeeper-lockfile-upload # Connection with Greenkeeper

cache:
  yarn: true
  directories:
     - ./node_modules

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test # Linting
      env: TEST=Lint
      script:
        - npm run lint
    
    - stage: test # Unit tests
      env: TEST=Unit tests
      script:
        - npm ci:test
    
    - stage: test # Unit tests
      env: TEST=e2e tests
      script:
        - xvfb-run -a npm run ci:e2e

    - stage: deploy # Deploy to DEV environment
      env: ENV=$HEROKU_APP_DEV
      if: type = push AND (NOT branch = master) # Deploy only run for PUSH, but avoid master
      deploy:
        provider: heroku
        app: $HEROKU_APP_DEV # This deployment is only for PR
        skip_cleanup: true
        api_key:
          - $HEROKU_TOKEN # Generated running heroku auth:token
        on:
          all_branches: true
