version: "2"
services:
  web:
    image: "samuelfernandez/portfolio"
    build: .
    user: "node"
    working_dir: "/usr/src/app"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/usr/src/app/
    expose:
     - "5000"
    command: "node server.js"
